# Reusable workflow for Firebase Hosting deploys
# Supports multiple apps via input parameters

name: Firebase Hosting Deploy
on:
  workflow_call:
    inputs:
      app_dir:
        required: true
        type: string
      project_id:
        required: true
        type: string
      channel_id:
        required: false
        type: string
        default: ""
    secrets:
      repo_token:
        required: true
      firebase_service_account:
        required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd ${{ inputs.app_dir }}
          npm ci
      - name: Build app
        run: |
          cd ${{ inputs.app_dir }}
          npm run build
      - name: Deploy to Firebase Hosting and Functions
        run: |
          cd ${{ inputs.app_dir }}
          npx firebase deploy --only hosting,functions --project ${{ inputs.project_id }} --token ${{ secrets.firebase_service_account }}